### PR TITLE
Apim 4 add get api key

### PR DESCRIPTION
**Pull request by sjrumsby**
Has all changes required for the 403 forbidden error messages to get pulled out of the swagger file.

### CODE REVIEW

**Comment by banders** [comment]
@sjrumsby The pull request says there are conflicts.  Can you check into that?

**Comment by sjrumsby** [comment]
Can you give me write access on your repo? I can through the conflicts that way? I guess otherwise I'd have to make a new branch off of my forked version of your gwa_integration branch and then reimplement my changes?

-Sean

**Comment by banders** [comment]
@sjrumsby Can you instead sync your forked repo with mine, then merge my branch (gwa-integration) with yours (APIM-4-Add_Get_Api_Key).  If you get conflicts you'll see them locally, resolve, commit, push, and finally create new pull request.  

Would that work?

**Comment by sjrumsby** [comment]
Ahhh, yes. That sounds like the git way to do it! Merged + new pull request submitted. Kong is still down, so I can’t really test it but everything is building and the HTTP errors I manually generate work as expected.

-Sean

**Comment by banders** [comment]
@sjrumsby Thanks.  I have delivered your latest code to the province.  We'll probably get some feedback in the next couple days.

**Pull request closed without merging**
