### PR TITLE
Apim 4 add get api key

### PR DESCRIPTION
**Pull request by sjrumsby**
Merging changes for fetching changes for the BC GWA API Key into upstream. URLs are pointing to wrong location for testing purposes, will be updated once CORS is enabled on the API.

### CODE REVIEW

**Review by banders — CHANGES_REQUESTED** [review]
Looks like you've requested a merge from your branch into the "master" branch of my repo.  Can you instead create the PR to merge into the "gwa-integration" branch of my repo?

**Comment by sjrumsby** [comment]
Ugh. #gitnoob

**Comment by sjrumsby** [comment]
I'll integrate the CORS enabled BC GWA stuff this evening and then issue a new pull request to the right branch.

-Sean

**Comment by banders** [comment]
ThanksBrock Anderson250-818-1270On Jun 27, 2017 1:48 PM, sjrumsby <notifications@github.com> wrote:I'll integrate the CORS enabled BC GWA stuff this evening and then issue a new pull request to the right branch.
-Sean

**Pull request closed without merging**
